name: birds
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - jupyterlab
  - tqdm
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pydot
  - scikit-learn
  - keras-gpu
  - tensorflow-gpu
  - cudatoolkit=9.0
  - pip:
    - gpustat
